// Common CFOP codes for internal operations
export const cfopCodes = [
  { code: "5101", desc: "Venda de produção do estabelecimento" },
  { code: "5102", desc: "Venda de mercadoria adquirida" },
  { code: "5111", desc: "Venda de produção do estab. sob encomenda" },
  { code: "5116", desc: "Venda de produção originada de encomenda" },
  { code: "5117", desc: "Venda de mercadoria adquirida originada de encomenda" },
  { code: "5151", desc: "Transferência de produção do estabelecimento" },
  { code: "5152", desc: "Transferência de mercadoria adquirida" },
  { code: "5201", desc: "Devolução de compra para industrialização" },
  { code: "5202", desc: "Devolução de compra para comercialização" },
  { code: "5401", desc: "Venda de produção em operação com ST" },
  { code: "5403", desc: "Venda de mercadoria sujeita a ST" },
  { code: "5405", desc: "Venda de mercadoria adquirida com ST" },
  { code: "5501", desc: "Remessa de produção p/ industrialização" },
  { code: "5551", desc: "Venda de bem do ativo imobilizado" },
  { code: "5556", desc: "Devolução de compra de material de uso" },
  { code: "5901", desc: "Remessa p/ industrialização por encomenda" },
  { code: "5902", desc: "Retorno de mercadoria p/ industrialização" },
  { code: "5910", desc: "Remessa em bonificação, doação ou brinde" },
  { code: "5911", desc: "Remessa de amostra grátis" },
  { code: "5927", desc: "Lançamento efetuado a título de baixa de estoque" },
  { code: "5949", desc: "Outra saída de mercadoria não especificada" },
  { code: "6101", desc: "Venda de produção (interestadual)" },
  { code: "6102", desc: "Venda de mercadoria adquirida (interestadual)" },
  { code: "6108", desc: "Venda de produção a não contribuinte" },
  { code: "6401", desc: "Venda de produção com ST (interestadual)" },
  { code: "6403", desc: "Venda de mercadoria sujeita a ST (interestadual)" },
  { code: "6949", desc: "Outra saída interestadual não especificada" },
  { code: "1101", desc: "Compra para industrialização" },
  { code: "1102", desc: "Compra para comercialização" },
  { code: "1551", desc: "Compra de bem para ativo imobilizado" },
  { code: "1556", desc: "Compra de material de uso e consumo" },
  { code: "2101", desc: "Compra para industrialização (interestadual)" },
  { code: "2102", desc: "Compra para comercialização (interestadual)" },
];

// CST codes (ICMS)
export const cstIcmsCodes = [
  { code: "000", desc: "Tributada integralmente" },
  { code: "010", desc: "Tributada com cobrança de ICMS por ST" },
  { code: "020", desc: "Com redução de base de cálculo" },
  { code: "030", desc: "Isenta/não tributada com cobrança de ICMS por ST" },
  { code: "040", desc: "Isenta" },
  { code: "041", desc: "Não tributada" },
  { code: "050", desc: "Suspensão" },
  { code: "051", desc: "Diferimento" },
  { code: "060", desc: "ICMS cobrado anteriormente por ST" },
  { code: "070", desc: "Com redução de BC e cobrança de ICMS por ST" },
  { code: "090", desc: "Outras" },
  { code: "100", desc: "Tributada pelo Simples com permissão de crédito (SN)" },
  { code: "101", desc: "Tributada pelo SN com permissão de crédito" },
  { code: "102", desc: "Tributada pelo SN sem permissão de crédito" },
  { code: "103", desc: "Isenção de ICMS para faixa de receita do SN" },
  { code: "201", desc: "Tributada com permissão de crédito e ST (SN)" },
  { code: "202", desc: "Tributada sem permissão de crédito e com ST (SN)" },
  { code: "300", desc: "Imune (SN)" },
  { code: "400", desc: "Não tributada (SN)" },
  { code: "500", desc: "ICMS cobrado anteriormente por ST (SN)" },
  { code: "900", desc: "Outros (SN)" },
];
