/**
 * Aliases e Mapas de Conversão para Importação
 */

// Mapeamento de unidades de medida comuns
export const UNIDADE_MEDIDA_ALIASES: Record<string, string> = {
  'UNID': 'UN',
  'UNIDADE': 'UN',
  'UNIDADES': 'UN',
  'PC': 'PC',
  'PEÇA': 'PC',
  'PEÇAS': 'PC',
  'KG': 'KG',
  'KILO': 'KG',
  'QUILO': 'KG',
  'LITRO': 'LT',
  'LITROS': 'LT',
  'LT': 'LT',
  'CX': 'CX',
  'CAIXA': 'CX',
  'DZ': 'DZ',
  'DUZIA': 'DZ',
  'M': 'M',
  'METRO': 'M',
  'M2': 'M2',
  'M3': 'M3',
  'PAR': 'PR',
  'PARES': 'PR',
};

// Mapeamento de status comuns
export const STATUS_IMPORTACAO_ALIASES: Record<string, string> = {
  'ATIVO': 'ativo',
  'INATIVO': 'inativo',
  'BLOQUEADO': 'bloqueado',
  'PENDENTE': 'pendente',
  'OK': 'ativo',
  'SIM': 'ativo',
  'NÃO': 'inativo',
  'NAO': 'inativo',
  '1': 'ativo',
  '0': 'inativo',
};

// Mapeamento de nomes de campos de planilhas para campos do sistema
export const FIELD_ALIASES: Record<string, string> = {
  // --- Chave legada ---
  'CODIGO LEGADO': 'codigo_legado',
  'CÓDIGO LEGADO': 'codigo_legado',
  'COD LEGADO': 'codigo_legado',
  'COD. LEGADO': 'codigo_legado',
  'CODLEG': 'codigo_legado',
  'ID LEGADO': 'codigo_legado',
  'REFERENCIA LEGADA': 'codigo_legado',
  'REFERÊNCIA LEGADA': 'codigo_legado',

  // --- Cadastros genéricos ---
  'NOME': 'nome',
  'RAZAO SOCIAL': 'nome',
  'RAZÃO SOCIAL': 'nome',
  'NOME FANTASIA': 'nome_fantasia',
  'CONTATO': 'contato',
  'CPF': 'cpf_cnpj',
  'CNPJ': 'cpf_cnpj',
  'CPF/CNPJ': 'cpf_cnpj',
  'INSCRICAO ESTADUAL': 'inscricao_estadual',
  'INSCRIÇÃO ESTADUAL': 'inscricao_estadual',
  'IE': 'inscricao_estadual',
  'TELEFONE': 'telefone',
  'FONE': 'telefone',
  'CELULAR': 'telefone',
  'EMAIL': 'email',
  'E-MAIL': 'email',
  'ENDERECO': 'logradouro',
  'ENDEREÇO': 'logradouro',
  'LOGRADOURO': 'logradouro',
  'CEP': 'cep',
  'CIDADE': 'cidade',
  'ESTADO': 'uf',
  'UF': 'uf',
  'BAIRRO': 'bairro',
  'NUMERO': 'numero',
  'NÚMERO': 'numero',
  'COMPLEMENTO': 'complemento',
  'OBSERVACOES': 'observacoes',
  'OBSERVAÇÕES': 'observacoes',

  // --- Produtos ---
  'CODIGO': 'codigo_interno',
  'CÓDIGO': 'codigo_interno',
  'SKU': 'codigo_interno',
  'DESCRIÇÃO': 'nome',
  'DESCRICAO': 'nome',
  'TIPO ITEM': 'tipo_item',
  'TIPO_ITEM': 'tipo_item',
  'TIPO': 'tipo_item',
  'VARIACOES': 'variacoes',
  'VARIAÇÕES': 'variacoes',
  'GRUPO': 'grupo',
  'CATEGORIA': 'grupo',
  'PRECO': 'preco_venda',
  'PREÇO': 'preco_venda',
  'PRECO VENDA': 'preco_venda',
  'PREÇO VENDA': 'preco_venda',
  'PRECO DE VENDA': 'preco_venda',
  'VALOR': 'preco_venda',
  'CUSTO': 'preco_custo',
  'PRECO CUSTO': 'preco_custo',
  'PREÇO CUSTO': 'preco_custo',
  'PRECO DE CUSTO': 'preco_custo',
  'PESO': 'peso',
  'ESTOQUE': 'estoque_atual',
  'QUANTIDADE': 'quantidade',
  'QTD': 'quantidade',
  'UNIDADE': 'unidade_medida',
  'UN': 'unidade_medida',
  'NCM': 'ncm',
  'GTIN': 'gtin',
  'EAN': 'gtin',

  // --- Estoque ---
  'CODIGO PRODUTO': 'codigo_produto',
  'CÓDIGO PRODUTO': 'codigo_produto',
  'COD PRODUTO': 'codigo_produto',
  'DATA ESTOQUE': 'data_estoque_inicial',
  'DATA DO ESTOQUE': 'data_estoque_inicial',
  'DATA INICIAL': 'data_estoque_inicial',
  'DEPOSITO': 'deposito',
  'DEPÓSITO': 'deposito',
  'LOCAL': 'deposito',
  'CUSTO UNITARIO': 'custo_unitario',
  'CUSTO UNITÁRIO': 'custo_unitario',

  // --- Financeiro ---
  'TIPO TITULO': 'tipo',
  'TIPO TÍTULO': 'tipo',
  'CR': 'tipo',
  'CP': 'tipo',
  'PAGAR_RECEBER': 'tipo',
  'PAGAR/RECEBER': 'tipo',
  'TITULO': 'titulo',
  'TÍTULO': 'titulo',
  'DOCUMENTO': 'titulo',
  'DOC': 'titulo',
  'NUMERO DOC': 'titulo',
  'PARCELA': 'parcela',
  'HISTORICO': 'descricao',
  'HISTÓRICO': 'descricao',
  'DESCR. FINANCEIRO': 'descricao',
  'DATA EMISSAO': 'data_emissao',
  'DATA EMISSÃO': 'data_emissao',
  'EMISSAO': 'data_emissao',
  'EMISSÃO': 'data_emissao',
  'VENCIMENTO': 'data_vencimento',
  'DATA VENCIMENTO': 'data_vencimento',
  'DATA DE VENCIMENTO': 'data_vencimento',
  'PAGAMENTO': 'data_pagamento',
  'DATA PAGAMENTO': 'data_pagamento',
  'DATA DE PAGAMENTO': 'data_pagamento',
  'DATA BAIXA': 'data_pagamento',
  'BAIXA': 'data_pagamento',
  'VALOR PAGO': 'valor_pago',
  'VLPAGO': 'valor_pago',
  'STATUS': 'status',
  'SITUACAO': 'status',
  'SITUAÇÃO': 'status',
  'BANCO': 'banco',
  'FORMA PAGAMENTO': 'forma_pagamento',
  'FORMA DE PAGAMENTO': 'forma_pagamento',

  // --- Faturamento ---
  'NOTA': 'numero_nota',
  'NUMERO NOTA': 'numero_nota',
  'NÚMERO NOTA': 'numero_nota',
  'NF': 'numero_nota',
  'CHAVE ACESSO': 'chave_acesso',
  'CHAVE DE ACESSO': 'chave_acesso',
  'DATA': 'data',
  'TOTAL': 'valor',
  'CLIENTE': 'cliente',
  'DESTINATARIO': 'cliente',
  'DESTINATÁRIO': 'cliente',
  'MUNICIPIO': 'municipio',
  'MUNICÍPIO': 'municipio',
  // Item fields
  'COD PRODUTO NF': 'codigo_produto_nf',
  'CODIGO PRODUTO NF': 'codigo_produto_nf',
  'PRODUTO': 'nome_produto',
  'DESCRICAO PRODUTO': 'nome_produto',
  'DESCRIÇÃO PRODUTO': 'nome_produto',
  'CFOP': 'cfop',
  'CST': 'cst',
  'QUANTIDADE NF': 'quantidade_nf',
  'QTD NF': 'quantidade_nf',
  'VALOR UNITARIO': 'valor_unitario',
  'VALOR UNITÁRIO': 'valor_unitario',
  'VALOR TOTAL': 'valor_total',
  'FRETE': 'frete_valor',
  'ICMS': 'icms_valor',
  'IPI': 'ipi_valor',
  'PIS': 'pis_valor',
  'COFINS': 'cofins_valor',
  'CUSTO PRODUTO': 'custo_produto',
  'LUCRO': 'lucro',
};
