/**
 * Aliases e Mapas de Conversão para Importação
 */

// Mapeamento de unidades de medida comuns
export const UNIDADE_MEDIDA_ALIASES: Record<string, string> = {
  'UNID': 'UN',
  'UNIDADE': 'UN',
  'UNIDADES': 'UN',
  'PC': 'PC',
  'PEÇA': 'PC',
  'PEÇAS': 'PC',
  'KG': 'KG',
  'KILO': 'KG',
  'QUILO': 'KG',
  'LITRO': 'LT',
  'LITROS': 'LT',
  'LT': 'LT',
  'CX': 'CX',
  'CAIXA': 'CX',
  'DZ': 'DZ',
  'DUZIA': 'DZ',
  'M': 'M',
  'METRO': 'M',
  'M2': 'M2',
  'M3': 'M3',
  'PAR': 'PR',
  'PARES': 'PR',
};

// Mapeamento de status comuns
export const STATUS_IMPORTACAO_ALIASES: Record<string, string> = {
  'ATIVO': 'ativo',
  'INATIVO': 'inativo',
  'BLOQUEADO': 'bloqueado',
  'PENDENTE': 'pendente',
  'OK': 'ativo',
  'SIM': 'ativo',
  'NÃO': 'inativo',
  'NAO': 'inativo',
  '1': 'ativo',
  '0': 'inativo',
};

// Mapeamento de nomes de campos de planilhas para campos do sistema
export const FIELD_ALIASES: Record<string, string> = {
  'NOME': 'nome',
  'RAZAO SOCIAL': 'nome',
  'RAZÃO SOCIAL': 'nome',
  'NOME FANTASIA': 'nome_fantasia',
  'CPF': 'cpf_cnpj',
  'CNPJ': 'cpf_cnpj',
  'CPF/CNPJ': 'cpf_cnpj',
  'TELEFONE': 'telefone',
  'FONE': 'telefone',
  'CELULAR': 'telefone',
  'EMAIL': 'email',
  'E-MAIL': 'email',
  'ENDERECO': 'endereco',
  'ENDEREÇO': 'endereco',
  'CEP': 'cep',
  'CIDADE': 'cidade',
  'ESTADO': 'uf',
  'UF': 'uf',
  'BAIRRO': 'bairro',
  'NUMERO': 'numero',
  'NÚMERO': 'numero',
  'COMPLEMENTO': 'complemento',
  'CODIGO': 'codigo_interno',
  'CÓDIGO': 'codigo_interno',
  'SKU': 'codigo_interno',
  'DESCRIÇÃO': 'descricao',
  'DESCRICAO': 'descricao',
  'PRECO': 'preco_venda',
  'PREÇO': 'preco_venda',
  'VALOR': 'preco_venda',
  'CUSTO': 'preco_custo',
  'ESTOQUE': 'estoque_atual',
  'QUANTIDADE': 'quantidade',
  'QTD': 'quantidade',
  'UNIDADE': 'unidade_medida',
  'UN': 'unidade_medida',
  'NCM': 'ncm',
  'GTIN': 'gtin',
  'EAN': 'gtin',
};
