/**
 * Slide definitions map for Apresentação Gerencial V1.
 * Each slide declares its metadata, chart type, data dependencies,
 * and comment template.
 */
import type { SlideDefinition, ApresentacaoRawData } from '@/types/apresentacao';

export const SLIDE_DEFINITIONS: SlideDefinition[] = [
  {
    codigo: 'cover',
    titulo: 'Fechamento Mensal',
    subtitulo: 'Apresentação Gerencial — AviZee',
    chartType: 'none',
    datasets: [],
    placeholders: ['periodo', 'empresa', 'data_geracao'],
    comentarioTemplate: 'Apresentação gerencial referente ao período {periodo}.',
    dependencias: [],
  },
  {
    codigo: 'highlights_financeiros',
    titulo: 'Highlights Financeiros',
    subtitulo: 'Visão geral do período',
    chartType: 'kpi_card',
    datasets: ['receita', 'despesa', 'resultado', 'recebido', 'pago'],
    placeholders: ['total_receita', 'total_despesa', 'resultado_bruto', 'variacao_receita', 'variacao_despesa'],
    comentarioTemplate: 'Receita {total_receita}; Despesa {total_despesa}; Resultado {resultado_bruto}.',
    dependencias: ['highlights'],
  },
  {
    codigo: 'faturamento',
    titulo: 'Faturamento',
    subtitulo: 'Evolução mensal do faturamento',
    chartType: 'coluna',
    datasets: ['total_faturado', 'quantidade_nfs'],
    placeholders: ['total_faturado', 'quantidade_nfs', 'variacao_faturamento'],
    comentarioTemplate: 'Faturamento de {total_faturado} com {quantidade_nfs} notas emitidas.',
    dependencias: ['faturamento'],
  },
  {
    codigo: 'despesas',
    titulo: 'Despesas',
    subtitulo: 'Distribuição e evolução das despesas',
    chartType: 'barra_horizontal',
    datasets: ['categoria', 'total_despesa'],
    placeholders: ['total_despesa', 'maior_categoria', 'variacao_despesa'],
    comentarioTemplate: 'Total de despesas: {total_despesa}. Maior categoria: {maior_categoria}.',
    dependencias: ['despesas'],
  },
  {
    codigo: 'rol_caixa',
    titulo: 'Caixa / ROL',
    subtitulo: 'Posição de caixa e contas bancárias',
    chartType: 'tabela',
    datasets: ['conta_descricao', 'banco_nome', 'saldo_atual'],
    placeholders: ['saldo_total', 'quantidade_contas'],
    comentarioTemplate: 'Saldo total em caixa: {saldo_total} distribuído em {quantidade_contas} contas.',
    dependencias: ['rolCaixa'],
  },
  {
    codigo: 'receita_vs_despesa',
    titulo: 'Receita vs Despesa',
    subtitulo: 'Comparativo mensal',
    chartType: 'linha',
    datasets: ['total_receita', 'total_despesa', 'resultado_bruto'],
    placeholders: ['total_receita', 'total_despesa', 'resultado_bruto'],
    comentarioTemplate: 'Receita {total_receita} vs Despesa {total_despesa}. Resultado: {resultado_bruto}.',
    dependencias: ['receitaVsDespesa'],
  },
  {
    codigo: 'fopag',
    titulo: 'FOPAG',
    subtitulo: 'Folha de pagamento',
    chartType: 'tabela',
    datasets: ['funcionario_nome', 'salario_base', 'proventos', 'descontos', 'valor_liquido'],
    placeholders: ['total_liquido', 'quantidade_funcionarios'],
    comentarioTemplate: 'Folha de pagamento: {quantidade_funcionarios} funcionários, total líquido {total_liquido}.',
    dependencias: ['fopag'],
  },
  {
    codigo: 'fluxo_caixa',
    titulo: 'Fluxo de Caixa',
    subtitulo: 'Entradas e saídas do período',
    chartType: 'coluna',
    datasets: ['total_entradas', 'total_saidas', 'saldo_periodo'],
    placeholders: ['total_entradas', 'total_saidas', 'saldo_periodo'],
    comentarioTemplate: 'Entradas {total_entradas}, saídas {total_saidas}. Saldo: {saldo_periodo}.',
    dependencias: ['fluxoCaixa'],
  },
  {
    codigo: 'lucro_produto_cliente',
    titulo: 'Lucro por Produto e Cliente',
    subtitulo: 'Top produtos e clientes por margem',
    chartType: 'barra_horizontal',
    datasets: ['produto_nome', 'cliente_nome', 'margem_bruta'],
    placeholders: ['top_produto', 'top_cliente', 'margem_total'],
    comentarioTemplate: 'Maior margem: produto {top_produto}, cliente {top_cliente}.',
    dependencias: ['lucro'],
    condicaoExibicao: (data: ApresentacaoRawData) => data.lucro.length > 0,
  },
  {
    codigo: 'variacao_estoque',
    titulo: 'Variação de Estoque',
    subtitulo: 'Posição e valor do estoque',
    chartType: 'tabela',
    datasets: ['produto_nome', 'grupo_nome', 'quantidade_atual', 'valor_total'],
    placeholders: ['valor_total_estoque', 'quantidade_itens'],
    comentarioTemplate: 'Estoque valorizado em {valor_total_estoque} com {quantidade_itens} itens ativos.',
    dependencias: ['estoque'],
  },
  {
    codigo: 'venda_estado',
    titulo: 'Venda por Estado',
    subtitulo: 'Distribuição geográfica das vendas',
    chartType: 'barra_horizontal',
    datasets: ['estado', 'total_vendas', 'quantidade_pedidos'],
    placeholders: ['top_estado', 'total_estados', 'total_vendas'],
    comentarioTemplate: 'Principal mercado: {top_estado}. Total de {total_estados} estados atendidos.',
    dependencias: ['vendaEstado'],
    condicaoExibicao: (data: ApresentacaoRawData) => data.vendaEstado.length > 0,
  },
  {
    codigo: 'redes_sociais',
    titulo: 'Redes Sociais',
    subtitulo: 'Performance nas plataformas digitais',
    chartType: 'tabela',
    datasets: ['plataforma', 'metrica', 'valor'],
    placeholders: ['plataformas_ativas'],
    comentarioTemplate: 'Dados de redes sociais: {plataformas_ativas} plataformas monitoradas.',
    dependencias: ['redesSociais'],
    condicaoExibicao: (data: ApresentacaoRawData) => data.redesSociais.length > 0,
  },
];

export function getSlideByCode(codigo: string): SlideDefinition | undefined {
  return SLIDE_DEFINITIONS.find((s) => s.codigo === codigo);
}
