
ALTER TABLE public.orcamentos ADD COLUMN IF NOT EXISTS desconto NUMERIC DEFAULT 0;
ALTER TABLE public.orcamentos ADD COLUMN IF NOT EXISTS imposto_st NUMERIC DEFAULT 0;
ALTER TABLE public.orcamentos ADD COLUMN IF NOT EXISTS imposto_ipi NUMERIC DEFAULT 0;
ALTER TABLE public.orcamentos ADD COLUMN IF NOT EXISTS outras_despesas NUMERIC DEFAULT 0;
