// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;

export const supabaseConfigError = !SUPABASE_URL
  ? "Configuração ausente: defina VITE_SUPABASE_URL no ambiente de publicação."
  : !SUPABASE_PUBLISHABLE_KEY
    ? "Configuração ausente: defina VITE_SUPABASE_PUBLISHABLE_KEY (ou VITE_SUPABASE_ANON_KEY) no ambiente de publicação."
    : null;

export const isSupabaseConfigured = !supabaseConfigError;

if (supabaseConfigError) {
  console.error("[Supabase] " + supabaseConfigError);
}

export const supabase = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : null;
