// This file is automatically generated. Do not edit it directly.
//
// SECURITY NOTE
// -------------
// `VITE_SUPABASE_PUBLISHABLE_KEY` is the Supabase **anon key** — it is public by
// design and safe to expose in the client bundle. Real authorization is enforced
// by Row Level Security (RLS) policies on the database side.
//
// **Never** put real secrets here (service_role key, certificate passwords,
// SMTP passwords, third-party API keys). Server-side secrets must live only in
// Edge Functions, accessed via `Deno.env.get(...)` and stored in the Supabase
// project secrets / Vault.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

/**
 * Lê uma `<meta name="...">` do `index.html`. Usado como fallback resiliente
 * em PWA instalado: se o chunk JS atual for um precache antigo onde
 * `import.meta.env.VITE_SUPABASE_*` foi compilado como string vazia, ainda
 * conseguimos inicializar o auth lendo do HTML (que é sempre fresco da rede
 * via navigateFallback do Workbox).
 */
function readMeta(name: string): string {
  if (typeof document === "undefined") return "";
  const el = document.querySelector(`meta[name="${name}"]`);
  return (el?.getAttribute("content") || "").trim();
}

const SUPABASE_URL =
  (import.meta.env.VITE_SUPABASE_URL as string) ||
  readMeta("x-supabase-url");
const SUPABASE_PUBLISHABLE_KEY =
  ((import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY) as string) ||
  readMeta("x-supabase-anon-key");
const isPlaceholderConfig =
  !SUPABASE_URL ||
  !SUPABASE_PUBLISHABLE_KEY ||
  SUPABASE_URL.includes("placeholder.supabase.co") ||
  SUPABASE_PUBLISHABLE_KEY === "placeholder";

export const isSupabaseConfigured = !isPlaceholderConfig;

if (!isSupabaseConfigured && typeof window !== "undefined") {
  // Diagnóstico: se cair no fallback "placeholder", o .env não foi injetado pelo Vite.
  // Force um rebuild (editar qualquer arquivo) ou hard refresh para corrigir.
  console.error("[supabase] VITE_SUPABASE_URL/KEY ausentes — usando placeholder. Faça hard refresh.");
}

export const supabase = createClient<Database>(
  SUPABASE_URL || "https://placeholder.supabase.co",
  SUPABASE_PUBLISHABLE_KEY || "placeholder",
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
