// This file is automatically generated. Do not edit it directly.
//
// SECURITY NOTE
// -------------
// `VITE_SUPABASE_PUBLISHABLE_KEY` is the Supabase **anon key** — it is public by
// design and safe to expose in the client bundle. Real authorization is enforced
// by Row Level Security (RLS) policies on the database side.
//
// **Never** put real secrets here (service_role key, certificate passwords,
// SMTP passwords, third-party API keys). Server-side secrets must live only in
// Edge Functions, accessed via `Deno.env.get(...)` and stored in the Supabase
// project secrets / Vault.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY) as string;

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

export const supabase = createClient<Database>(
  SUPABASE_URL || "https://placeholder.supabase.co",
  SUPABASE_PUBLISHABLE_KEY || "placeholder",
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
